# Generated by Django 5.2.4 on 2026-07-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_contact_alter_blog_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional label for admin / image alt text', max_length=150)),
                ('image', models.ImageField(upload_to='instagram/')),
                ('link', models.URLField(blank=True, default='https://www.instagram.com/natureholidayskerala/', help_text='Instagram post or profile URL opened when the icon is clicked')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram Post',
                'verbose_name_plural': 'Instagram Posts',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
