# Generated by Django 5.2.4 on 2026-07-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_instagrampost'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Background photo for this slide. If empty, the site uses the default static hero image.', null=True, upload_to='hero/')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(help_text='Main headline. Use a line break in the template via title_line_2 if set.', max_length=255)),
                ('title_line_2', models.CharField(blank=True, help_text='Optional second line of the headline (renders under the first line).', max_length=255)),
                ('button_text', models.CharField(default='Plan my trip', max_length=80)),
                ('button_link', models.CharField(default='/packages/', help_text='URL or path for the CTA button (e.g. /packages/ or a full URL).', max_length=255)),
                ('stat_1_value', models.CharField(blank=True, default='18+', max_length=40)),
                ('stat_1_label', models.CharField(blank=True, default='Years experience', max_length=80)),
                ('stat_2_value', models.CharField(blank=True, default='4.9★', max_length=40)),
                ('stat_2_label', models.CharField(blank=True, default='Customer rating', max_length=80)),
                ('stat_3_value', models.CharField(blank=True, default='200+', max_length=40)),
                ('stat_3_label', models.CharField(blank=True, default='Happy reviews', max_length=80)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SitePageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_bg', models.ImageField(blank=True, help_text='Background behind the home About section', null=True, upload_to='site/about/', verbose_name='Home about background')),
                ('about_main', models.ImageField(blank=True, help_text='Primary photo in the home About collage', null=True, upload_to='site/about/', verbose_name='Home about main image')),
                ('about_secondary', models.ImageField(blank=True, help_text='Secondary overlapping photo in the home About collage', null=True, upload_to='site/about/', verbose_name='Home about secondary image')),
                ('about_badge_title', models.CharField(blank=True, default='Care you can feel', help_text='Blue badge title on the home About collage', max_length=80)),
                ('about_badge_subtitle', models.CharField(blank=True, default='18 years of experience', help_text='Blue badge subtitle (e.g. years of experience)', max_length=120)),
                ('choose_us_bg', models.ImageField(blank=True, help_text='Full-section background for Why Choose Us', null=True, upload_to='site/choose-us/', verbose_name='Choose us background')),
                ('choose_us_image', models.ImageField(blank=True, help_text='Side photograph for Why Choose Us', null=True, upload_to='site/choose-us/', verbose_name='Choose us side image')),
                ('about_page_main', models.ImageField(blank=True, help_text='Primary photo on the About page collage', null=True, upload_to='site/about/', verbose_name='About page main image')),
                ('about_page_secondary', models.ImageField(blank=True, help_text='Secondary photo on the About page collage', null=True, upload_to='site/about/', verbose_name='About page secondary image')),
                ('breadcrumb_bg', models.ImageField(blank=True, help_text='Background used on inner-page breadcrumb banners', null=True, upload_to='site/breadcrumb/', verbose_name='Breadcrumb background')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Page Media',
                'verbose_name_plural': 'Site Page Media',
            },
        ),
    ]
