# Generated by Django 5.2.4 on 2026-07-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_hero_slide_and_site_page_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctasection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='cta/'),
        ),
    ]
